### ISSUE TITLE
Integrating styled-components with React Server Components example

### ISSUE THREAD

**Issue by Jacksonmills** [bholmesdev/simple-rsc#8]
I've been exploring the simple-rsc repo and I'm interested in integrating styled-components with React Server Components. I wanted to get your thoughts on whether it's a good direction to take.

src/Title.js:
```javascript
'use client';

import styled from "styled-components";

const Title = styled.h1``;

export default Title;
```

Then, we can update the page.jsx file to use the Title styled-component:

src/page.jsx:
```javascript
import { Suspense } from "react";
import { getAll, getById } from "../db/fetch.js";
import SearchableAlbumList from "./SearchableAlbumList";
import Title from "../client/Title";

export default async function ServerRoot({ search }) {
  return (
    <>
      <Title>Welcome to server components?</Title>
      <h2>Search results for "{search}"</h2>
      <Suspense fallback={<h2>Loading...</h2>}>
        <Albums search={search} />
      </Suspense>
    </>
  );
}

async function Albums({ search }) {
  const albums = await getAll();
  return (
    <SearchableAlbumList search={search} albums={albums} />
  );
}
```

Would you consider this a viable approach to add styled-components to React Server Components?

I'd appreciate your insight and any recommendations on best practices for this integration, especially since integrating styled-components with SSR can be challenging to begin with.

Cheers!

**Comment by bholmesdev** [comment]
Hey @Jacksonmills! Appreciate the request here; definitely agree styled components support makes for a great migration story. I'll confess this tool uses [esbuild](https://esbuild.github.io/) for bundling components, which avoids the need for Babel and other "traditional" React plugins. This makes for quick builds and a human-readable `dist` folder... at the expense of fewer supported libraries. I'll confess styled components are on that list.

styled-components have been notoriously hard to support in [Vite](https://vitejs.dev/)-backed tools today (which also relies on esbuild), so I'm not sure they're in-scope for this project. If you want to take a stab at a PR, go for it! Though I'm not sure it will work stably without some fundamental changes.

**Comment by Jacksonmills** [comment]
Totally @bholmesdev mostly just curious and wanted to throw out there as we explore RSC more
