### ISSUE TITLE
Support Webpack

### ISSUE THREAD

**Issue by damassi** [bholmesdev/simple-rsc#9]
Hi! So exciting to see a new RSC demo in the wild, we've needed something like this for a while. 

Curious if there's any plans to support React's RSC webpack plugin in the demo? I like how this is a bit more vanilla, but it would also be cool to see a version that uses more official tooling.

**Comment by bholmesdev** [comment]
Thanks @damassi! To be honest... I started with webpack tooling and scrapped it after a few hours of tinkering. Wasn't able to find a minimal config that worked, though that's 100% from my own lack of experience with webpack. For now, [there is an official webpack demo](https://github.com/reactjs/server-components-demo) from the React team! Would like to pair this down to a simplified build step. Perhaps a `build.webpack.js` file we'll call with a flag. Contributions are open if you're willing to submit a PR as well 🙂

**Comment by damassi** [comment]
Oh look at that -- the official repo has been updated as of last week! I mentioned this here because I thought React's version was still stale, and this repo is the first i've seen with the latest conventions. 

Will close 👍

**Comment by damassi** [comment]
Also, for those who are curious, there's this repo that I just discovered from dan: https://github.com/unstubbable/mfng, which appears to be the most complete implementation that isn't Next.
